In [7]:
import pandas as pd
# Read the CSV files
results_df = pd.read_csv("results.csv")

results_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
0,50,50,0.4,0.25,10,0.01,0.5,0.2,0.10,0.1,33.359651,33.866149,2025-01-30 20:33:25
1,50,50,0.4,0.25,10,0.05,0.5,0.2,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
2,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,32.798641,33.418512,2025-01-30 20:40:21
3,30,40,0.3,0.25,5,0.10,0.8,0.2,0.10,0.1,31.697887,32.484707,2025-01-30 20:54:26
4,30,40,0.3,0.25,5,0.30,0.8,0.2,0.10,0.1,32.501605,33.081095,2025-01-30 21:44:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.827533,5.928053,2025-02-15 20:05:00
145,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.809872,5.924145,2025-02-15 20:35:50
146,50,500,0.6,0.25,4,0.01,0.5,0.2,0.21,0.1,4.988684,5.063692,2025-02-15 20:42:45
147,100,500,0.6,0.25,4,0.01,0.8,0.2,0.01,0.1,3.504411,3.521500,2025-02-15 20:52:52
148,100,200,0.8,0.25,4,0.01,0.8,0.2,0.01,0.1,4.298415,4.313342,2025-02-15 20:57:33

In [ ]:
sorted_df = results_df.sort_values(by="best_fitness", ascending=True)
sorted_df

In [ ]:
latest_df = sorted_df.sort_values(by="timestamp", ascending=False)   
latest_df

In [15]:
import pandas as pd
results0_df = pd.read_csv("GenRec0Results.csv")
results0_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
0,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.563169,4.584721,5.775552,2025-02-19 02_45_47,00:00:54
1,50,100,0.8,0.40,4,0.01,0.8,0.2,0.030,0.1,4.655108,4.677918,5.502420,2025-02-19 02_46_42,00:01:12
2,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.586751,4.606375,6.070075,2025-02-19 02_47_55,00:01:00
3,50,100,0.4,0.40,4,0.01,0.8,0.2,0.030,0.1,4.408260,4.438919,5.829327,2025-02-19 02_48_55,00:00:40
4,50,100,0.6,0.10,4,0.01,0.8,0.2,0.030,0.1,4.650034,4.670636,5.499565,2025-02-19 02_49_36,00:00:56
5,50,100,0.6,0.30,4,0.01,0.8,0.2,0.030,0.1,4.610420,4.629759,5.889173,2025-02-19 02_50_32,00:00:57
6,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.806434,4.838750,5.831816,2025-02-19 02_51_29,00:00:55
7,50,100,0.6,0.60,4,0.01,0.8,0.2,0.030,0.1,4.494364,4.525046,5.976969,2025-02-19 02_52_25,00:00:55
8,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.573520,4.588839,5.877056,2025-02-19 02_53_20,00:00:55
9,50,100,0.6,0.40,4,0.01,0.8,0.2,0.001,0.1,5.046590,5.052491,5.802548,2025-02-19 02_54_16,00:00:55
10,50,100,0.6,0.40,4,0.01,0.8,0.2,0.010,0.1,4.749338,4.764147,5.716842,2025-02-19 02_55_12,00:00:54
11,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.481804,4.502563,6.106174,2025-02-19 02_56_06,00:00:55
12,50,100,0.6,0.40,4,0.01,0.8,0.2,0.100,0.1,4.450336,4.486920,6.017482,2025-02-19 02_57_02,00:00:55
13,50,100,0.6,0.40,4,0.01,0.8,0.2,0.060,0.1,4.653229,4.684346,6.008160,2025-02-19 02_57_57,00:00:56
14,50,100,0.6,0.40,2,0.01,0.8,0.2,0.030,0.1,4.563142,4.603496,5.910373,2025-02-19 02_58_53,00:00:55
15,50,100,0.6,0.40,5,0.01,0.8,0.2,0.030,0.1,4.768902,4.785059,6.211591,2025-02-19 02_59_49,00:00:55
16,50,100,0.6,0.40,8,0.01,0.8,0.2,0.030,0.1,4.744563,4.766840,6.020852,2025-02-19 03_00_44,00:00:55
17,50,100,0.6,0.40,10,0.01,0.8,0.2,0.030,0.1,4.755987,4.772449,6.105285,2025-02-19 03_01_39,00:00:55
18,50,100,0.6,0.40,15,0.01,0.8,0.2,0.030,0.1,4.757219,4.774799,5.871772,2025-02-19 03_02_34,00:00:55
19,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.523634,4.550838,5.902277,2025-02-19 03_03_29,00:00:58
20,30,100,0.3,0.25,12,0.01,0.8,0.2,0.300,0.1,4.366143,4.409437,5.995546,2025-03-06 14_38_23,00:00:27
21,30,500,0.3,0.25,12,0.01,0.8,0.2,0.300,0.1,3.493419,3.528849,6.290604,2025-03-06 14_40_03,00:01:50
22,30,1000,0.3,0.25,12,0.01,0.8,0.2,0.300,0.1,3.043970,3.085794,6.287373,2025-03-06 14_42_19,00:03:34
23,30,200,0.8,0.25,12,0.01,0.8,0.2,0.300,0.1,4.559932,4.594351,5.760335,2025-03-06 14_46_14,00:02:06

In [16]:
sorted0_df = results0_df.sort_values(by="test_score", ascending=True)
sorted0_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
4,50,100,0.6,0.10,4,0.01,0.8,0.2,0.030,0.1,4.650034,4.670636,5.499565,2025-02-19 02_49_36,00:00:56
1,50,100,0.8,0.40,4,0.01,0.8,0.2,0.030,0.1,4.655108,4.677918,5.502420,2025-02-19 02_46_42,00:01:12
10,50,100,0.6,0.40,4,0.01,0.8,0.2,0.010,0.1,4.749338,4.764147,5.716842,2025-02-19 02_55_12,00:00:54
23,30,200,0.8,0.25,12,0.01,0.8,0.2,0.300,0.1,4.559932,4.594351,5.760335,2025-03-06 14_46_14,00:02:06
0,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.563169,4.584721,5.775552,2025-02-19 02_45_47,00:00:54
9,50,100,0.6,0.40,4,0.01,0.8,0.2,0.001,0.1,5.046590,5.052491,5.802548,2025-02-19 02_54_16,00:00:55
3,50,100,0.4,0.40,4,0.01,0.8,0.2,0.030,0.1,4.408260,4.438919,5.829327,2025-02-19 02_48_55,00:00:40
6,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.806434,4.838750,5.831816,2025-02-19 02_51_29,00:00:55
18,50,100,0.6,0.40,15,0.01,0.8,0.2,0.030,0.1,4.757219,4.774799,5.871772,2025-02-19 03_02_34,00:00:55
8,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.573520,4.588839,5.877056,2025-02-19 02_53_20,00:00:55
5,50,100,0.6,0.30,4,0.01,0.8,0.2,0.030,0.1,4.610420,4.629759,5.889173,2025-02-19 02_50_32,00:00:57
19,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.523634,4.550838,5.902277,2025-02-19 03_03_29,00:00:58
14,50,100,0.6,0.40,2,0.01,0.8,0.2,0.030,0.1,4.563142,4.603496,5.910373,2025-02-19 02_58_53,00:00:55
7,50,100,0.6,0.60,4,0.01,0.8,0.2,0.030,0.1,4.494364,4.525046,5.976969,2025-02-19 02_52_25,00:00:55
20,30,100,0.3,0.25,12,0.01,0.8,0.2,0.300,0.1,4.366143,4.409437,5.995546,2025-03-06 14_38_23,00:00:27
13,50,100,0.6,0.40,4,0.01,0.8,0.2,0.060,0.1,4.653229,4.684346,6.008160,2025-02-19 02_57_57,00:00:56
12,50,100,0.6,0.40,4,0.01,0.8,0.2,0.100,0.1,4.450336,4.486920,6.017482,2025-02-19 02_57_02,00:00:55
16,50,100,0.6,0.40,8,0.01,0.8,0.2,0.030,0.1,4.744563,4.766840,6.020852,2025-02-19 03_00_44,00:00:55
2,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.586751,4.606375,6.070075,2025-02-19 02_47_55,00:01:00
17,50,100,0.6,0.40,10,0.01,0.8,0.2,0.030,0.1,4.755987,4.772449,6.105285,2025-02-19 03_01_39,00:00:55
11,50,100,0.6,0.40,4,0.01,0.8,0.2,0.030,0.1,4.481804,4.502563,6.106174,2025-02-19 02_56_06,00:00:55
15,50,100,0.6,0.40,5,0.01,0.8,0.2,0.030,0.1,4.768902,4.785059,6.211591,2025-02-19 02_59_49,00:00:55
22,30,1000,0.3,0.25,12,0.01,0.8,0.2,0.300,0.1,3.043970,3.085794,6.287373,2025-03-06 14_42_19,00:03:34
21,30,500,0.3,0.25,12,0.01,0.8,0.2,0.300,0.1,3.493419,3.528849,6.290604,2025-03-06 14_40_03,00:01:50

In [17]:
results1_df = pd.read_csv("GenRec1Results.csv")
results1_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
0,20,20,0.4,0.10,4,0.100,0.8,0.4,0.400,0.1,32.403075,32.924089,34.532178,2025-02-17 01:02:40,NaN
1,20,20,0.4,0.10,4,0.050,0.8,0.4,0.400,0.1,32.876474,33.465806,33.797322,2025-02-17 01:14:52,NaN
2,20,50,0.8,0.10,4,0.001,0.8,0.4,0.010,0.1,32.592425,32.715610,33.652973,2025-02-17 01:24:54,NaN
3,20,200,0.8,0.10,4,0.001,0.8,0.4,0.010,0.1,32.084048,32.196978,35.145406,2025-02-17 01:39:35,NaN
4,20,200,0.8,0.50,4,0.001,0.8,0.4,0.010,0.5,31.779213,31.986337,33.727452,2025-02-17 01:58:07,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,30,150,0.8,0.40,2,0.001,0.8,0.4,0.005,0.5,32.653029,32.981374,34.733892,2025-02-18 12_59_12,NaN
147,30,15,0.8,0.40,2,0.001,0.8,0.4,0.005,0.5,33.739779,34.231222,34.143315,2025-02-18 21_43_57,00:01:11
148,50,100,0.6,0.40,4,0.010,0.8,0.2,0.030,0.1,32.737827,33.164052,33.763801,2025-02-19 03_18_09,00:09:22
149,50,50,0.3,0.25,5,0.010,0.8,0.2,0.030,0.1,33.162703,33.844275,34.140965,2025-02-19 03_32_36,00:13:31
150,30,100,0.3,0.25,12,0.010,0.8,0.2,0.300,0.1,30.768409,31.265877,33.782917,2025-03-06 14_32_38,00:04:26

In [18]:
sorted1_df = results1_df.sort_values(by="test_score", ascending=True)
sorted1_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
144,20,10,0.8,0.50,4,0.001,0.80,0.4,0.01,0.5,33.594898,33.967684,32.885108,2025-02-17 22_00_05,NaN
2,20,50,0.8,0.10,4,0.001,0.80,0.4,0.01,0.1,32.592425,32.715610,33.652973,2025-02-17 01:24:54,NaN
4,20,200,0.8,0.50,4,0.001,0.80,0.4,0.01,0.5,31.779213,31.986337,33.727452,2025-02-17 01:58:07,NaN
148,50,100,0.6,0.40,4,0.010,0.80,0.2,0.03,0.1,32.737827,33.164052,33.763801,2025-02-19 03_18_09,00:09:22
150,30,100,0.3,0.25,12,0.010,0.80,0.2,0.30,0.1,30.768409,31.265877,33.782917,2025-03-06 14_32_38,00:04:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,20,40,0.4,0.05,2,0.330,0.23,0.2,0.49,0.1,33.172409,33.631685,NaN,2025-01-31 00:34:36,NaN
136,20,40,0.4,0.05,2,0.330,0.23,0.2,0.51,0.1,33.172934,33.637344,NaN,2025-01-31 00:36:45,NaN
137,20,150,0.3,0.05,2,0.330,0.23,0.2,0.03,0.1,33.127834,33.368920,NaN,2025-01-31 00:45:50,NaN
138,20,150,0.3,0.05,2,0.330,0.23,0.2,0.03,0.1,32.806848,33.039127,NaN,2025-01-31 01:05:47,NaN
139,20,150,0.3,0.25,5,0.010,0.80,0.2,0.01,0.1,30.452496,30.608713,NaN,2025-01-31 01:12:21,NaN

In [2]:
import pandas as pd
#benchmark against common methods for collaborative filtering
#three methods will be used
#matrix factorization(svd)
#label-propogation(semi supervised)
#highbrid model specifiaclly light-fm(hybrid matrix facorixzation using NN)
import os
datafolder = "datafiles"
final_df_path = os.path.join(datafolder,"final_df.pkl")
#check if the file exists
if os.path.exists(final_df_path):
    #load the final dataframe
    df = pd.read_pickle(final_df_path)

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error



# Split items per user into train/test
splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(splitter.split(df, groups=df["user"]))

train_df = df.iloc[train_idx]
test_df = df.iloc[test_idx]

# Create masked user-item matrices (train has NaNs for test items)
user_item_train = train_df.pivot(index="user", columns="item", values="rating")
user_item_test = test_df.pivot(index="user", columns="item", values="rating")

# Align matrices to include all users and items
all_users = df["user"].unique()
all_items = df["item"].unique()
user_item_train = user_item_train.reindex(index=all_users, columns=all_items)
user_item_test = user_item_test.reindex(index=all_users, columns=all_items)

# Convert to numpy arrays (NaN for unobserved entries)
R_train = user_item_train.values
R_test = user_item_test.values

In [4]:
from sklearn.decomposition import TruncatedSVD

# Fill NaN with 0 (or user/item mean)
R_train_filled = np.nan_to_num(R_train, nan=0)

# Fit SVD on training data
n_components = 50
svd = TruncatedSVD(n_components=n_components)
user_factors = svd.fit_transform(R_train_filled)
item_factors = svd.components_

# Predict ratings: U * V^T
R_pred_svd = user_factors @ item_factors

# Extract test predictions and true ratings
test_mask = ~np.isnan(R_test)
y_true = R_test[test_mask]
y_pred_svd = R_pred_svd[test_mask]

# Calculate metrics
rmse_svd = np.sqrt(mean_squared_error(y_true, y_pred_svd))
mae_svd = mean_absolute_error(y_true, y_pred_svd)

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute user similarity matrix on training data
W_train = cosine_similarity(R_train_filled)

# Predict test ratings using similar users' ratings
R_pred_lp = np.zeros_like(R_test)
for (u, i) in zip(*np.where(test_mask)):
    # Find users who rated item i in the train set
    rated_users = np.where(~np.isnan(R_train[:, i]))[0]
    if len(rated_users) == 0:
        # Fallback to global mean if no ratings
        R_pred_lp[u, i] = np.nanmean(R_train)
    else:
        # Weighted average of similar users' ratings
        similarities = W_train[u, rated_users]
        ratings = R_train[rated_users, i]
        R_pred_lp[u, i] = np.dot(similarities, ratings) / (np.sum(similarities) + 1e-9)

# Extract predictions and calculate metrics
y_pred_lp = R_pred_lp[test_mask]
rmse_lp = np.sqrt(mean_squared_error(y_true, y_pred_lp))
mae_lp = mean_absolute_error(y_true, y_pred_lp)

In [6]:
results = {
    "Method": ["SVD", "Label Propagation"],
    "RMSE": [rmse_svd, rmse_lp],
    "MAE": [mae_svd, mae_lp]
}

results_df = pd.DataFrame(results)
print(results_df)

              Method      RMSE       MAE
0                SVD  7.566995  7.260278
1  Label Propagation  7.566995  7.260278