In [2]:
import pandas as pd
# Read the CSV files
results_df = pd.read_csv("results.csv")

results_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
0,50,50,0.4,0.25,10,0.01,0.5,0.2,0.10,0.1,33.359651,33.866149,2025-01-30 20:33:25
1,50,50,0.4,0.25,10,0.05,0.5,0.2,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
2,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,32.798641,33.418512,2025-01-30 20:40:21
3,30,40,0.3,0.25,5,0.10,0.8,0.2,0.10,0.1,31.697887,32.484707,2025-01-30 20:54:26
4,30,40,0.3,0.25,5,0.30,0.8,0.2,0.10,0.1,32.501605,33.081095,2025-01-30 21:44:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.827533,5.928053,2025-02-15 20:05:00
145,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.809872,5.924145,2025-02-15 20:35:50
146,50,500,0.6,0.25,4,0.01,0.5,0.2,0.21,0.1,4.988684,5.063692,2025-02-15 20:42:45
147,100,500,0.6,0.25,4,0.01,0.8,0.2,0.01,0.1,3.504411,3.521500,2025-02-15 20:52:52
148,100,200,0.8,0.25,4,0.01,0.8,0.2,0.01,0.1,4.298415,4.313342,2025-02-15 20:57:33

In [33]:
sorted_df = results_df.sort_values(by="best_fitness", ascending=True)
sorted_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
36,100,500,0.6,0.25,5,0.01,0.80,0.20,0.01,0.1,3.402483,3.415809,2025-02-14 13:53:50
29,100,500,0.6,0.25,5,0.01,0.80,0.20,0.01,0.1,3.485530,3.496258,2025-02-03 23:39:39
37,100,500,0.6,0.10,5,0.50,0.80,0.30,0.50,0.1,3.815436,3.954106,2025-02-14 14:01:46
30,100,500,0.6,0.10,5,0.50,0.80,0.30,0.50,0.1,3.885733,4.009497,2025-02-03 23:47:40
25,25,500,0.6,0.25,2,0.30,0.50,0.05,0.30,0.1,4.327443,4.356099,2025-01-31 01:50:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,20,40,0.4,0.05,2,0.33,0.27,0.20,0.10,0.1,33.536611,34.044042,2025-01-30 23:02:14
1,50,50,0.4,0.25,10,0.05,0.50,0.20,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
131,20,40,0.4,0.05,2,0.33,0.23,0.20,0.33,0.1,33.573782,33.962401,2025-01-31 00:19:14
22,25,30,0.6,0.25,2,0.30,0.50,0.05,0.30,0.1,33.599354,33.937279,2025-01-31 01:45:29
61,20,40,0.4,0.80,5,0.01,0.50,0.20,0.10,0.1,33.695860,34.087188,2025-01-30 21:41:41

In [32]:
latest_df = sorted_df.sort_values(by="timestamp", ascending=False)   
latest_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
144,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.827533,5.928053,2025-02-15 20:05:00
143,100,50,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.457843,5.524301,2025-02-15 20:01:23
40,50,20,0.4,0.10,4,0.10,0.8,0.4,0.40,0.1,32.945978,33.858875,2025-02-15 10:54:24
39,100,50,0.6,0.25,5,0.01,0.8,0.2,0.01,0.1,5.005000,5.021572,2025-02-15 10:48:35
38,100,50,0.6,0.25,5,0.01,0.8,0.2,0.01,0.1,4.871515,4.899884,2025-02-15 10:45:17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,30,40,0.4,0.25,5,0.01,0.5,0.2,0.10,0.1,33.318269,33.966886,2025-01-30 20:52:47
41,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,31.943082,32.715915,2025-01-30 20:49:34
2,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,32.798641,33.418512,2025-01-30 20:40:21
1,50,50,0.4,0.25,10,0.05,0.5,0.2,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
0,50,50,0.4,0.25,10,0.01,0.5,0.2,0.10,0.1,33.359651,33.866149,2025-01-30 20:33:25

In [23]:
import pandas as pd
results0_df = pd.read_csv("GenRec0Results.csv")
results0_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
0,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.563169,4.584721,5.775552,2025-02-19 02_45_47,00:00:54
1,50,100,0.8,0.4,4,0.01,0.8,0.2,0.030,0.1,4.655108,4.677918,5.502420,2025-02-19 02_46_42,00:01:12
2,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.586751,4.606375,6.070075,2025-02-19 02_47_55,00:01:00
3,50,100,0.4,0.4,4,0.01,0.8,0.2,0.030,0.1,4.408260,4.438919,5.829327,2025-02-19 02_48_55,00:00:40
4,50,100,0.6,0.1,4,0.01,0.8,0.2,0.030,0.1,4.650034,4.670636,5.499565,2025-02-19 02_49_36,00:00:56
5,50,100,0.6,0.3,4,0.01,0.8,0.2,0.030,0.1,4.610420,4.629759,5.889173,2025-02-19 02_50_32,00:00:57
6,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.806434,4.838750,5.831816,2025-02-19 02_51_29,00:00:55
7,50,100,0.6,0.6,4,0.01,0.8,0.2,0.030,0.1,4.494364,4.525046,5.976969,2025-02-19 02_52_25,00:00:55
8,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.573520,4.588839,5.877056,2025-02-19 02_53_20,00:00:55
9,50,100,0.6,0.4,4,0.01,0.8,0.2,0.001,0.1,5.046590,5.052491,5.802548,2025-02-19 02_54_16,00:00:55
10,50,100,0.6,0.4,4,0.01,0.8,0.2,0.010,0.1,4.749338,4.764147,5.716842,2025-02-19 02_55_12,00:00:54
11,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.481804,4.502563,6.106174,2025-02-19 02_56_06,00:00:55
12,50,100,0.6,0.4,4,0.01,0.8,0.2,0.100,0.1,4.450336,4.486920,6.017482,2025-02-19 02_57_02,00:00:55
13,50,100,0.6,0.4,4,0.01,0.8,0.2,0.060,0.1,4.653229,4.684346,6.008160,2025-02-19 02_57_57,00:00:56
14,50,100,0.6,0.4,2,0.01,0.8,0.2,0.030,0.1,4.563142,4.603496,5.910373,2025-02-19 02_58_53,00:00:55
15,50,100,0.6,0.4,5,0.01,0.8,0.2,0.030,0.1,4.768902,4.785059,6.211591,2025-02-19 02_59_49,00:00:55
16,50,100,0.6,0.4,8,0.01,0.8,0.2,0.030,0.1,4.744563,4.766840,6.020852,2025-02-19 03_00_44,00:00:55
17,50,100,0.6,0.4,10,0.01,0.8,0.2,0.030,0.1,4.755987,4.772449,6.105285,2025-02-19 03_01_39,00:00:55
18,50,100,0.6,0.4,15,0.01,0.8,0.2,0.030,0.1,4.757219,4.774799,5.871772,2025-02-19 03_02_34,00:00:55
19,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.523634,4.550838,5.902277,2025-02-19 03_03_29,00:00:58

In [25]:
sorted0_df = results0_df.sort_values(by="test_score", ascending=True)
sorted0_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
4,50,100,0.6,0.1,4,0.01,0.8,0.2,0.030,0.1,4.650034,4.670636,5.499565,2025-02-19 02_49_36,00:00:56
1,50,100,0.8,0.4,4,0.01,0.8,0.2,0.030,0.1,4.655108,4.677918,5.502420,2025-02-19 02_46_42,00:01:12
10,50,100,0.6,0.4,4,0.01,0.8,0.2,0.010,0.1,4.749338,4.764147,5.716842,2025-02-19 02_55_12,00:00:54
0,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.563169,4.584721,5.775552,2025-02-19 02_45_47,00:00:54
9,50,100,0.6,0.4,4,0.01,0.8,0.2,0.001,0.1,5.046590,5.052491,5.802548,2025-02-19 02_54_16,00:00:55
3,50,100,0.4,0.4,4,0.01,0.8,0.2,0.030,0.1,4.408260,4.438919,5.829327,2025-02-19 02_48_55,00:00:40
6,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.806434,4.838750,5.831816,2025-02-19 02_51_29,00:00:55
18,50,100,0.6,0.4,15,0.01,0.8,0.2,0.030,0.1,4.757219,4.774799,5.871772,2025-02-19 03_02_34,00:00:55
8,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.573520,4.588839,5.877056,2025-02-19 02_53_20,00:00:55
5,50,100,0.6,0.3,4,0.01,0.8,0.2,0.030,0.1,4.610420,4.629759,5.889173,2025-02-19 02_50_32,00:00:57
19,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.523634,4.550838,5.902277,2025-02-19 03_03_29,00:00:58
14,50,100,0.6,0.4,2,0.01,0.8,0.2,0.030,0.1,4.563142,4.603496,5.910373,2025-02-19 02_58_53,00:00:55
7,50,100,0.6,0.6,4,0.01,0.8,0.2,0.030,0.1,4.494364,4.525046,5.976969,2025-02-19 02_52_25,00:00:55
13,50,100,0.6,0.4,4,0.01,0.8,0.2,0.060,0.1,4.653229,4.684346,6.008160,2025-02-19 02_57_57,00:00:56
12,50,100,0.6,0.4,4,0.01,0.8,0.2,0.100,0.1,4.450336,4.486920,6.017482,2025-02-19 02_57_02,00:00:55
16,50,100,0.6,0.4,8,0.01,0.8,0.2,0.030,0.1,4.744563,4.766840,6.020852,2025-02-19 03_00_44,00:00:55
2,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.586751,4.606375,6.070075,2025-02-19 02_47_55,00:01:00
17,50,100,0.6,0.4,10,0.01,0.8,0.2,0.030,0.1,4.755987,4.772449,6.105285,2025-02-19 03_01_39,00:00:55
11,50,100,0.6,0.4,4,0.01,0.8,0.2,0.030,0.1,4.481804,4.502563,6.106174,2025-02-19 02_56_06,00:00:55
15,50,100,0.6,0.4,5,0.01,0.8,0.2,0.030,0.1,4.768902,4.785059,6.211591,2025-02-19 02_59_49,00:00:55

In [6]:
results1_df = pd.read_csv("GenRec1Results.csv")
results1_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp,duration
0,20,20,0.4,0.1,4,0.100,0.8,0.4,0.400,0.1,32.403075,32.924089,34.532178,2025-02-17 01:02:40,NaN
1,20,20,0.4,0.1,4,0.050,0.8,0.4,0.400,0.1,32.876474,33.465806,33.797322,2025-02-17 01:14:52,NaN
2,20,50,0.8,0.1,4,0.001,0.8,0.4,0.010,0.1,32.592425,32.715610,33.652973,2025-02-17 01:24:54,NaN
3,20,200,0.8,0.1,4,0.001,0.8,0.4,0.010,0.1,32.084048,32.196978,35.145406,2025-02-17 01:39:35,NaN
4,20,200,0.8,0.5,4,0.001,0.8,0.4,0.010,0.5,31.779213,31.986337,33.727452,2025-02-17 01:58:07,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,20,20,0.8,0.5,4,0.001,0.8,0.4,0.010,0.5,33.270305,33.669863,33.893978,2025-02-17 14_31_46,NaN
144,20,10,0.8,0.5,4,0.001,0.8,0.4,0.010,0.5,33.594898,33.967684,32.885108,2025-02-17 22_00_05,NaN
145,20,30,0.8,0.5,2,0.001,0.8,0.4,0.005,0.5,33.105347,33.403261,33.883068,2025-02-18 12_56_00,NaN
146,30,150,0.8,0.4,2,0.001,0.8,0.4,0.005,0.5,32.653029,32.981374,34.733892,2025-02-18 12_59_12,NaN
147,30,15,0.8,0.4,2,0.001,0.8,0.4,0.005,0.5,33.739779,34.231222,34.143315,2025-02-18 21_43_57,00:01:11

In [6]:
sorted1_df = results1_df.sort_values(by="best_fitness", ascending=True)
sorted1_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp
31,50,500,0.3,0.20,6,0.100,0.80,0.20,0.10,0.1,29.979104,30.558290,NaN,2025-02-03 15:46:57
139,20,150,0.3,0.25,5,0.010,0.80,0.20,0.01,0.1,30.452496,30.608713,NaN,2025-01-31 01:12:21
30,50,500,0.3,0.25,10,0.010,0.80,0.20,0.01,0.1,30.488510,31.183906,NaN,2025-02-03 15:03:40
22,25,100,0.3,0.20,12,0.100,0.80,0.90,0.30,0.1,31.077278,31.479451,NaN,2025-01-31 00:56:42
20,50,100,0.3,0.20,12,0.100,0.80,0.90,0.20,0.1,31.272781,32.354477,NaN,2025-01-31 00:51:04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,50,50,0.4,0.25,10,0.050,0.50,0.20,0.10,0.1,33.544466,33.996070,NaN,2025-01-30 20:36:49
128,20,40,0.4,0.05,2,0.330,0.23,0.20,0.33,0.1,33.573782,33.962401,NaN,2025-01-31 00:19:14
144,20,10,0.8,0.50,4,0.001,0.80,0.40,0.01,0.5,33.594898,33.967684,32.885108,2025-02-17 22_00_05
29,25,30,0.6,0.25,2,0.300,0.50,0.05,0.30,0.1,33.599354,33.937279,NaN,2025-01-31 01:45:29
58,20,40,0.4,0.80,5,0.010,0.50,0.20,0.10,0.1,33.695860,34.087188,NaN,2025-01-30 21:41:41

In [3]:
#benchmark against common methods for collaborative filtering
#three methods will be used
#matrix factorization(svd)
#label-propogation(semi supervised)
#highbrid model specifiaclly light-fm(hybrid matrix facorixzation using NN)
import os
datafolder = "datafiles"
final_df_path = os.path.join(datafolder,"final_df.pkl")
#check if the file exists
if os.path.exists(final_df_path):
    #load the final dataframe
    final_df = pd.read_pickle(final_df_path)

In [4]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Compute affinity matrix
user_item_matrix = final_df.pivot_table(index="user", columns="item", values="rating").fillna(0)
W = cosine_similarity(user_item_matrix)
np.fill_diagonal(W, 0)  # No self-similarity

# Label propagation
D = np.diag(W.sum(axis=1) + 1e-5)  # Degree matrix
Y = user_item_matrix.values.copy()  # Known ratings
Y_unknown = np.isnan(Y)

for _ in range(20):  # Iterate until convergence
    Y_new = np.linalg.solve(D, W @ Y)
    Y[Y_unknown] = Y_new[Y_unknown]

In [ ]:
import lightgbm as lgb